### PR TITLE
Example loading an OpenFAST output file 

### PR DESCRIPTION
**Pull request by ptrbortolotti**
Hello @dingraha,
thank you for your work! Your repository has been extremely useful for us at the [National Renewable Energy Lab](https://www.nrel.gov), especially during the [Big Adaptive Rotor project](https://www.nrel.gov/wind/big-adaptive-rotor.html), where we have been simulating the low-frequency noise emissions of a GE 1.5 MW wind turbine operated in a downwind rotor configuration. For more details about the experiment, please take a look [here](https://www.osti.gov/biblio/2205317).

In this pull request, I add an example where AcousticAnalogies.jl is run after loading an output file (.out) of [OpenFAST](https://github.com/OpenFAST/openfast). 

OpenFAST is a physics-based engineering tool for simulating the coupled dynamic response of wind turbines. OpenFAST joins aerodynamics models, hydrodynamics models for offshore structures, control and electrical system (servo) dynamics models, and structural (elastic) dynamics models to enable coupled nonlinear aero- hydro-servo-elastic simulation in the time domain. 

OpenFAST is fully open-source and in this example I used it to simulate the aerodynamic loading of the rotor of a [3.4MW](https://github.com/IEAWindTask37/IEA-3.4-130-RWT) land-based reference wind turbine, which was designed and released by the International Energy Agency Wind Task 37 on Systems Engineering. The turbine faces a wind speed of 8 m/s and its rotor spins close to 8 rpm.

I've tried my best to conform my new code to your code practices. This said, I welcome feedback and edits to this PR.

Again, here at NREL we greatly appreciate this collaboration!

### CODE REVIEW

**Comment by dingraha** [comment]
@ptrbortolotti Sorry I haven't gotten to this yet. Haven't forgotten, and I will finish it off soon. :-)

**Comment by ptrbortolotti** [comment]
hello @dingraha, just checking in about this PR. Please let me know if you need me to change anything, and thank you!

**Comment by dingraha** [comment]
@ptrbortolotti I apologize for not getting to this. There are a few changes I want to make that I'm working my way through. It's made it's way to the top of my priority list, so I should be able to finish it off soon.

**Comment by dingraha** [comment]
@ptrbortolotti I think I have everything in place now. Would you mind having a look at https://github.com/ptrbortolotti/AcousticAnalogies.jl/blob/main/docs/src/openfast_example.md and see what you think before we merge?

**Review by ptrbortolotti — COMMENTED** [review]
this all looks great, thank you! @maricemina is working on the validation and we will be in touch once she has results to show

**Pull request merged**
